Mq-b/Loser-HomeWork

src/群友提交/第一题/mq松鼠.cpp
=> mq squirrel这次总对了吧 第一题

src/群友提交/第一题/joe.cpp
管道运算符就是利用左边的输出作为右边的输入，这一点搞清就行了。
=> 提交第一题（Create joe.cpp）

src/群友提交/第七题/Ninter6.cc
=> Ninter6第七题

src/群友提交/第七题/DarkSharpness.cpp
I also added some test functions. Enjoy it~
=> Update my answer and my ideal implement for 7th exercise.

src/群友提交/第七题/27Onion.cc
=> feat: added 27Onion.cc for problem 7

src/群友提交/第八题/Wgtteol.cpp
=> feat: Wgtteol Homework_8.

src/群友提交/第八题/jacky.cpp
=> 8th: add jacky's lu'se homework

src/群友提交/第八题/mickey_8.cpp
=> problem 8, add concept to require T & U are the same type

README.md
=> 成功修改目录字体大小，打败99%C++大神

src/群友提交/第八题/saidfljwnzjasf.cpp
=> Submit Assignment 8

src/群友提交/第二题/Wgtteol.cpp
=> feat: Submit Wgtteol's homework_2.

src/群友提交/第九题/jacky.md
=> 9th jacky work

src/群友提交/第三题/Wgtteol.cpp
=> faet: Commit Wgtteol's homework_3.

README.md, src/群友提交/第一题/SocialMean.cpp, src/群友提交/第三题/SocialMean.cpp, src/群友提交/第二题/SocialMean.cpp
=> add: SoicalMean 1,2,3题

src/群友提交/第10题/jacky.cpp
=> add jacky 10th

src/群友提交/第10题/jacky.cpp, src/群友提交/第10题/jacky.md
=> update jacky 10th and add solution

src/群友提交/第10题/Wgtteol.cpp
=> feat : Commit Wgtteol's homework.

src/群友提交/第10题/Matrix-A.cpp
https://gcc.godbolt.org/z/9Gqdn39nK
=> Matrix-A 第十题

src/群友提交/第05题/Wgtteol.cpp
I learned again！ love you mq白❤
=> feat: Commit Wgtteol's homework_5.

src/群友提交/第06题/Wgtteol.md
=> feat: Commit Wgtteol's Homework_6.

src/群友提交/第11题/jacky.md
=> add jacky 11th solution

src/群友提交/第12题/Matrix-A.cpp
https://gcc.godbolt.org/z/7z3M9hPsv
=> Matrix-A 第12题

src/群友提交/第12题/jacky.cpp
=> add 12th jacky solution

src/群友提交/第13题/jacky.md
=> jacky 13th solution

src/群友提交/第01题/fywc.cpp
=> first problem

src/群友提交/第14题/Matrix-A-1.cpp
https://gcc.godbolt.org/z/eTeYeo1sd
思路为直接解析指令求得 ss::a 的指针
=> 又一种解法 Matrix-A-1.cpp

src/群友提交/第02题/蓝弧.cpp
=> 第二题fix bug

src/群友提交/第10题/Matrix-A-P1061.cpp
1. 使用C++26中的提案，[P1061](https://wg21.link/P1061)
2. 修改size函数为类似于std::size传入对象的形式
https://godbolt.org/z/d8hanTefc
注：修改size函数原因是因为，size函数内部没有通用的方法创建聚合初始化对象
=> 第10题 使用C++26提案中的新特性

README.md
=> Cpp-template

src/群友提交/第10题/Matrix-A-reflect.cpp
[reflect-ts](https://cplusplus.github.io/reflection-ts/draft.pdf)
[学习链接](https://clementpirelli.wordpress.com/2021/12/08/cpp-reflection-ts-first-look/)
https://godbolt.org/z/e6Gz3EEcc
注：不支持引用类型，疑似reflect::get_pointer不支持引用，以后再看
=> 第10题 基于反射技术规范的实现

src/群友提交/第14题/jacky.cpp
=> jacky's 14 luse

src/群友提交/第10题/Matrix-A.cpp
增加对以下情况的处理
```cpp
struct A{ int a{ 1 }; double b[2]{ 2.3, 3.4 }; std::string c{ "5" }; };
size<A>();
size<A[2]>();
```
https://godbolt.org/z/eWhr518se
注：因为计算个数没有使用`花括号消除`，无法对`std::array`处理（`std::array`使用元组式结构化绑定）
```cpp
size<std::array<int,2>>(); // 返回值为1，因为只有一个成员 _Elems （msvc）
auto&& [x] = std::array<int,2>{0,1}; // error
```
注：自定义元组式结构化绑定
https://godbolt.org/z/rWqhn899n
```cpp
#include <cstdio>
#include <cmath>
#include <iostream>
#include <vector>
//#include <format>
#include <stdexcept>
#include <new>
#include <array>
#include <utility> 
#include <tuple> 
#include <ranges> 
#include <cstdint>
struct A {
std::vector<int> v{ 0x123, 0x234 };
};
template<>
struct std::tuple_size<A> {
static constexpr std::size_t value{ 2 };
};
template<>
struct std::tuple_element<0, A> {
using type = int; …
```
=> 修改不能处理聚合类存在数组的错误，增加测试用例

README.md
Fix #159
代 @Matrix-A 为提交（#159）。
在原文基础上增添、删改了一些内容，以符合标准。
=> 卢瑟作业第15题（#159）

README.md
1. 移除部分编译器未支持的print
2. 添加 运行结果、群友提交、标准答案等小标题
=> 更新第15题 README.md

src/群友提交/第14题/Matrix-A.cpp
移除恶心人的属性，更改为使用 volatile 和 stomic 来保证在优化的情况下的正常执行修改为100后输出ss::a
在线编译： https://gcc.godbolt.org/z/o9chb1dM5
MSVC在release 和 debug 模式下也可以正确执行
=> 第14题 Update Matrix-A.cpp

src/群友提交/第10题/akchilov2.md
=> 关于第十题提交的同名cpp的解释

README.md
=> 添加README折叠

README.md
=> 修复README目录bug

src/群友提交/第14题/Matrix-A.cpp
修改 `std::atomic_flag` 为 `std::atomic_thread_fence`
https://gcc.godbolt.org/z/T4hTGcf16
=> Update Matrix-A.cpp 更优雅的设置内存定序

src/群友提交/第01题/CodeyZ.cpp, src/群友提交/第02题/CodeyZ.cpp, src/群友提交/第03题/CodeyZ.cpp
=> CodeyZ-first-pr

src/群友提交/第04题/CodeyZ.cpp
=> CodeyZ-sec-pr

src/卢瑟日经/C++ 包管理，编译构建配置等问题.md
`CMake` 于3.17引入了[`Ninja Multi-Config`](https://cmake.org/cmake/help/latest/generator/Ninja%20Multi-Config.html)。
=> [日经] 使用`Ninja Multi-Config`
